language: python
python:
  - "2.7"
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.2
install:
  - pip install -q coverage pep8 pyflakes Django==$DJANGO
  - pip install -q -e .
before_script:
  - pep8 localized_recurrence --max-line-length=120 --exclude=migrations
  - pyflakes localized_recurrence
script:
  - coverage run --source='localized_recurrence' --branch setup.py test
  - coverage report --fail-under=100